import uvicorn
from fastapi import FastAPI, Form, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from services.face_service import register_face, face_login
from input_types import ChatRequest, ChatResponse
from langchain_core.messages import HumanMessage
from agents.main_agent import compiled_graph
from dotenv import load_dotenv

load_dotenv()
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def home():
    return {"success": True, "message": "AgroSmart AI Server Running"}


@app.post("/register-face")
async def register_face_route(
    userId: str = Form(...), faceImage: UploadFile = File(...)
):
    return await register_face(userId, faceImage)


@app.post("/face-login")
async def face_login_route(faceImage: UploadFile = File(...)):
    print("File Name:", faceImage.filename)

    content = await faceImage.read()

    print("File Size:", len(content))

    await faceImage.seek(0)

    return await face_login(faceImage)


@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """Receive a prompt and return a simple text response until the full agent graph is wired in."""
    print("the  main file receving the payload", request.json())
    try:
        print(
            f"📥 Chat API triggered for User: {request.userId} | Prompt: {request.prompt}|{request.longitude}|{request.latitude}"
        )

        if not request.prompt.strip():
            raise HTTPException(status_code=400, detail="Prompt is required")

        inputs = {
            "messages": [HumanMessage(content=request.prompt)],
            "latitude": request.latitude,
            "longitude": request.longitude,
            "userId": request.userId,
        }

        # Set thread_id equal to the userId so history stays segmented per individual account
        # config = {"configurable": {"thread_id": request.userId}}
        config = {
            "configurable": {
                "thread_id": request.userId,
                "latitude": request.latitude,
                "longitude": request.longitude,
            }
        }
        # Invoke the graph state processing sequence
        output = compiled_graph.invoke(inputs, config=config)

        # Extract the last message generated by the pipeline (the final agent summary response)
        final_message = output["messages"][-1].content

        return ChatResponse(status="success", reply=str(final_message))
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error during chat processing: {e}")
        raise HTTPException(status_code=500, detail=f"Chat processing failed: {str(e)}")


if __name__ == "__main__":
    # Correct way to run FastAPI within a script
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
