import json
import uvicorn
from fastapi import FastAPI, Form, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from services.face_service import register_face, face_login
from input_types import ChatRequest, ChatResponse
from langchain_core.messages import HumanMessage, ToolMessage
from agents.main_agent import compiled_graph
from dotenv import load_dotenv
from pydantic import ValidationError
load_dotenv()
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def home():
    return {"success": True, "message": "AgroSmart AI Server Running"}


@app.post("/register-face")
async def register_face_route(
    userId: str = Form(...), faceImage: UploadFile = File(...)
):
    return await register_face(userId, faceImage)


@app.post("/face-login")
async def face_login_route(faceImage: UploadFile = File(...)):
    print("File Name:", faceImage.filename)

    content = await faceImage.read()

    print("File Size:", len(content))

    await faceImage.seek(0)

    return await face_login(faceImage)


# @app.post("/chat")
# async def chat_endpoint(request: ChatRequest):
#     """Receive a prompt and return the AI response plus any structured tool data."""
#     print("the  main file receving the payload", request.json())
#     try:
#         print(
#             f"📥 Chat API triggered for User: {request.userId} | Prompt: {request.prompt}|{request.longitude}|{request.latitude} |language:{request.language}"
#         )

#         if not request.prompt.strip():
#             raise HTTPException(status_code=400, detail="Prompt is required")

#         inputs = {
#             "messages": [HumanMessage(content=request.prompt)],
#             "latitude": request.latitude,
#             "longitude": request.longitude,
#             "userId": request.userId,
#         }

#         # Set thread_id equal to the userId so history stays segmented per individual account
#         config = {
#             "configurable": {
#                 "thread_id": request.userId,
#                 "latitude": request.latitude,
#                 "longitude": request.longitude,
#                 "language":request.language,
#             }
#         }
#         print("config data is the ",config)
#         # Invoke the graph state processing sequence
#         output = compiled_graph.invoke(inputs, config=config)

#         # Extract the last message generated by the pipeline (the final agent summary response)
#         final_message = output["messages"][-1].content
#         reply_text = str(final_message)

#         tool_message = None
#         for message in reversed(output.get("messages", [])):
#             if isinstance(message, ToolMessage):
#                 tool_message = message
#                 break

#         response_type = "text"
#         response_data = None

#         if tool_message is not None:
#             tool_name = getattr(tool_message, "name", None)
#             tool_content = tool_message.content

#             if isinstance(tool_content, str):
#                 try:
#                     parsed_content = json.loads(tool_content)
#                 except (TypeError, ValueError):
#                     parsed_content = tool_content
#             else:
#                 parsed_content = tool_content

#             if isinstance(parsed_content, list):
#                 response_data = parsed_content
#             elif isinstance(parsed_content, dict):
#                 response_data = [parsed_content]
#             elif parsed_content is not None:
#                 response_data = [parsed_content]

#             if tool_name == "get_agro_store":
#                 response_type = "agro_store"
#             elif tool_name == "get_agriculture_experts":
#                 response_type = "expert"
#             elif tool_name == "get_weather":
#                 response_type = "weather"
#             elif tool_name == "get_market_prices":
#                 response_type = "market_price"

#         return {
#             "status": "success",
#             "type": response_type,
#             "reply": reply_text,
#             "data": response_data,
#         }
#     except HTTPException:
#         raise
#     except Exception as e:
#         print(f"❌ Error during chat processing: {e}")
#         raise HTTPException(status_code=500, detail=f"Chat processing failed: {str(e)}")



@app.post("/chat")
async def chat_endpoint(
    photo: UploadFile = File(None),
    payload: str = Form(...)
):
    """Receive metadata and an image for your custom local pipeline."""
    try:
        # 1. Parse and validate using your Pydantic ChatRequest schema
        try:
            json_data = json.loads(payload)
            request = ChatRequest(**json_data)
        except (json.JSONDecodeError, ValidationError) as e:
            raise HTTPException(status_code=422, detail=f"Invalid payload structure: {str(e)}")

        print(f"📥 Request from User: {request.userId} | Language: {request.language}")

        # 2. Process image bytes directly for your own model
        # Safe default state so LangGraph nodes don't crash when reading it
        model_predictions = {
            "detected_issue": None, 
            "confidence": 0.0
        }

        if photo:
            image_bytes = await photo.read()
            print(f"📸 Running custom model on uploaded file: {photo.filename}")
            
            # --- CHOOSE ONE OPTION BELOW DEPENDING ON YOUR MODEL ---
            
            # Option A: If your model requires a PIL Image object
            # from PIL import Image
            # import io
            # pil_image = Image.open(io.BytesIO(image_bytes)).convert("RGB")
            
            # Option B: If your model processes via OpenCV / NumPy
            # import numpy as np
            # import cv2
            # np_array = np.frombuffer(image_bytes, np.uint8)
            # opencv_image = cv2.imdecode(np_array, cv2.IMREAD_COLOR)
            
            # Option C: Pass bytes directly to your inference pipeline wrapper
            # model_predictions = my_trained_model.predict(image_bytes)
            
            # Mock response placeholder (Replace with your actual model call)
            model_predictions = {
                "detected_issue": "Leaf Rust Disease", 
                "confidence": 0.94
            } 
            
        print("the detected disease is:", model_predictions)

        # 3. Feed the prompt metadata alongside your custom model data into LangGraph
        inputs = {
            "messages": [HumanMessage(content=request.prompt)], 
            "latitude": request.latitude,
            "longitude": request.longitude,
            "userId": request.userId,
            "custom_model_output": model_predictions, # Guaranteed to be a valid dictionary structure
             "language": request.language,
        }

        config = {
            "configurable": {
                "thread_id": request.userId,
                "latitude": request.latitude,
                "longitude": request.longitude,
                "language": request.language,
            }
        }
        
        # Execute your compiled LangGraph workflow pipeline
        print("config data is:", config)
        print("input state is:", inputs)
        
        output = compiled_graph.invoke(inputs, config=config)

        # Extract last message
        final_message = output["messages"][-1].content
        reply_text = str(final_message)

        tool_message = None
        for message in reversed(output.get("messages", [])):
            if isinstance(message, ToolMessage):
                tool_message = message
                break

        response_type = "text"
        response_data = None

        if tool_message is not None:
            tool_name = getattr(tool_message, "name", None)
            tool_content = tool_message.content

            if isinstance(tool_content, str):
                try: 
                    parsed_content = json.loads(tool_content)
                except (TypeError, ValueError): 
                    parsed_content = tool_content
            else:
                parsed_content = tool_content

            if isinstance(parsed_content, list): 
                response_data = parsed_content
            elif isinstance(parsed_content, dict): 
                response_data = [parsed_content]
            elif parsed_content is not None: 
                response_data = [parsed_content]

            if tool_name == "get_agro_store": 
                response_type = "agro_store"
            elif tool_name == "get_agriculture_experts": 
                response_type = "expert"
            elif tool_name == "get_weather": 
                response_type = "weather"
            elif tool_name == "get_market_prices": 
                response_type = "market_price"

        return {
            "status": "success",
            "type": response_type,
            "reply": reply_text,
            "data": response_data,
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error during processing: {e}")
        raise HTTPException(status_code=500, detail=f"Processing failed: {str(e)}")
if __name__ == "__main__":
    # Correct way to run FastAPI within a script
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
