import json
import uvicorn
from fastapi import FastAPI, Form, File, UploadFile, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from services.face_service import register_face, face_login
from input_types import ChatRequest, ChatResponse
from langchain_core.messages import HumanMessage, ToolMessage
from agents.main_agent import compiled_graph
from dotenv import load_dotenv

load_dotenv()
app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def home():
    return {"success": True, "message": "AgroSmart AI Server Running"}


@app.post("/register-face")
async def register_face_route(
    userId: str = Form(...), faceImage: UploadFile = File(...)
):
    return await register_face(userId, faceImage)


@app.post("/face-login")
async def face_login_route(faceImage: UploadFile = File(...)):
    print("File Name:", faceImage.filename)

    content = await faceImage.read()

    print("File Size:", len(content))

    await faceImage.seek(0)

    return await face_login(faceImage)


@app.post("/chat")
async def chat_endpoint(request: ChatRequest):
    """Receive a prompt and return the AI response plus any structured tool data."""
    print("the  main file receving the payload", request.json())
    try:
        print(
            f"📥 Chat API triggered for User: {request.userId} | Prompt: {request.prompt}|{request.longitude}|{request.latitude}"
        )

        if not request.prompt.strip():
            raise HTTPException(status_code=400, detail="Prompt is required")

        inputs = {
            "messages": [HumanMessage(content=request.prompt)],
            "latitude": request.latitude,
            "longitude": request.longitude,
            "userId": request.userId,
        }

        # Set thread_id equal to the userId so history stays segmented per individual account
        config = {
            "configurable": {
                "thread_id": request.userId,
                "latitude": request.latitude,
                "longitude": request.longitude,
            }
        }

        # Invoke the graph state processing sequence
        output = compiled_graph.invoke(inputs, config=config)

        # Extract the last message generated by the pipeline (the final agent summary response)
        final_message = output["messages"][-1].content
        reply_text = str(final_message)

        tool_message = None
        for message in reversed(output.get("messages", [])):
            if isinstance(message, ToolMessage):
                tool_message = message
                break

        response_type = "text"
        response_data = None

        if tool_message is not None:
            tool_name = getattr(tool_message, "name", None)
            tool_content = tool_message.content

            if isinstance(tool_content, str):
                try:
                    parsed_content = json.loads(tool_content)
                except (TypeError, ValueError):
                    parsed_content = tool_content
            else:
                parsed_content = tool_content

            if isinstance(parsed_content, list):
                response_data = parsed_content
            elif isinstance(parsed_content, dict):
                response_data = [parsed_content]
            elif parsed_content is not None:
                response_data = [parsed_content]

            if tool_name == "get_agro_store":
                response_type = "agro_store"
            elif tool_name == "get_agriculture_experts":
                response_type = "expert"
            elif tool_name == "get_weather":
                response_type = "weather"
            elif tool_name == "get_market_prices":
                response_type = "market_price"

        return {
            "status": "success",
            "type": response_type,
            "reply": reply_text,
            "data": response_data,
        }
    except HTTPException:
        raise
    except Exception as e:
        print(f"❌ Error during chat processing: {e}")
        raise HTTPException(status_code=500, detail=f"Chat processing failed: {str(e)}")


if __name__ == "__main__":
    # Correct way to run FastAPI within a script
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
